<a href="https://colab.research.google.com/github/KrishnaKumarAgawalla/PythonDataAnalysis/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

# **Basic Numpy Arrays**

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0,.5,1,1.5,2])

In [5]:
a[0], a[1]  #Print individual elements 

(1, 2)

In [6]:
a[0:] #from index 0 to upper limit(last index) of array a

array([1, 2, 3, 4])

In [7]:
a[1:3] #from index 1 to 2 (upper index not included)

array([2, 3])

In [8]:
a[1:-1] #negative indexing can also be used 

array([2, 3])

For the array a the negative index are as follows [-4, -3, -2, -1] So, a[1:-1] starts from index 1 (value 2) and goes till -2 (value 3) can also be written as a[1:3]

In [9]:
a[::2] #From the 0th index till last index step 2 so printed indexes are 0,2,4,...

array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1] 

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]] #multi Indexing

array([0., 1., 2.])

The Result for the above (multi indexing) is another numpy array which while processing will take space due to creation of a new array

# Array Types

In [13]:
a #prints array a

array([1, 2, 3, 4])

In [14]:
a.dtype #prints the type of array a

dtype('int64')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

by default the numpy type is base64

In [17]:
np.array([1,2,3,4], dtype=np.float_) #dtype can be used to tune the type of data
                                     #according to need so even if the array was
                                     #int type it got stored as float 

array([1., 2., 3., 4.])

In [18]:
np.array([1,2,3,4], dtype=np.int8) #smaller integers can be used for more
                                   #performance for small data

array([1, 2, 3, 4], dtype=int8)

In [19]:
c = np.array(['a', 'b', 'c'])

In [20]:
c.dtype  #stored as unicode

dtype('<U1')

In [21]:
d= np.array([{'a': 1}, sys]) #numpy stores numbers, date, strings (As unicode), 
                             #etc but not regular individual objects

In [22]:
d.dtype 

dtype('O')

# **Dimension & Shapes**

In [23]:
A = np.array([
    [1, 2, 3 ],
    [4,5,6]
])

In [24]:
A.shape  #give rows and colomns of matrix

(2, 3)

In [25]:
A.ndim #gives the dimension of the matrix

2

In [26]:
A.size  #gives the size of the matrix (total number of elements)

6

In [27]:
B = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [28]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
B.shape

(2, 2, 3)

In [30]:
B.ndim

3

In [31]:
B.size

12

If dimensions don't match it will go back to regular Python objects

In [32]:
C = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9]
    ]
])

<ipython-input-32-58b8a0b5a4a9>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [33]:
C.dtype

dtype('O')

In [34]:
C.shape  #gives 2 as only 2 elements are now present 1 array containing 1 - 6
         #2nd array containing 7 - 9

(2,)

In [35]:
C.size

2

In [36]:
type(C[0])

list

# **Indexing & Slicing**

In [37]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [38]:
A[1]

array([4, 5, 6])

In [39]:
A[1] [0]

4

In [40]:
A[1, 0]

4

In [41]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [43]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [44]:
A[:2, 2:]

array([[3],
       [6]])

In [45]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
A[1] = np.array([10,10,10])  #Replaces the entire 2nd row with [10,10,10]

In [47]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [48]:
A[2] = 90  #Replaces the entire 3rd row with [90,90,90]

In [49]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [90, 90, 90]])

# Statistics

In [50]:
a = np.array([1,2,3,4])

In [51]:
a.sum()

10

In [52]:
a.mean()

2.5

In [53]:
a.std()

1.118033988749895

In [54]:
a.var()

1.25

In [55]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [56]:
A.sum()

45

In [57]:
A.mean()

5.0

In [58]:
A.std()

2.581988897471611

In [59]:
A.sum(axis=0)  #gives sum of elements of each column

array([12, 15, 18])

In [60]:
A.sum(axis=1) #gives sum of elements of each row

array([ 6, 15, 24])

In [61]:
A.mean(axis=0)

array([4., 5., 6.])

In [62]:
A.mean(axis=1)

array([2., 5., 8.])

In [63]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [64]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

# **Broadcasting and Vectorized operations**

In [65]:
a = np.arange(4)  #makes an array from 0 to n-1

In [66]:
a

array([0, 1, 2, 3])

In [67]:
a + 10  #broadcasts addition of 10 to each individaul element and creats a new array

array([10, 11, 12, 13])

In [68]:
a * 10

array([ 0, 10, 20, 30])

In [69]:
a  #original array unchanged as a nw array was created

array([0, 1, 2, 3])

In [70]:
a += 100  #Same as above but instead of creating a new array original array gets overwritten

In [71]:
a #Array got overwritten with modified values

array([100, 101, 102, 103])

In [72]:
l = [0,1,2,3]

In [73]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [74]:
a = np.arange(4)

In [75]:
a

array([0, 1, 2, 3])

In [76]:
b = np.array([10,10,10,10])

In [77]:
a + b  #Addition between coressponding elements Needs to be of same shape

array([10, 11, 12, 13])

In [78]:
a * b

array([ 0, 10, 20, 30])

# **Boolean Arrays**

In [79]:
a = np.arange(4)

In [80]:
a

array([0, 1, 2, 3])

In [81]:
a[0], a[-1]   #Selecting elements of 1st and last index

(0, 3)

In [82]:
a[[0, -1]]    #Same operation but using multi indexing

array([0, 3])

In [83]:
a[[True,False,False,True]]  #SAme opration with boolean arrays
                            #True index is sleected and False is not

array([0, 3])

In [84]:
a >=2   #compares all the individual elements and gives the boolean array

array([False, False,  True,  True])

In [85]:
a[a >= 2]   #becomes the same operation as Selecting elements with boolean array
            #as a>=2 gives an array as can be seen from the above example

array([2, 3])

In [86]:
a.mean()

1.5

In [87]:
a[a > a.mean()]   #all elements greater than the mean

array([2, 3])

In [88]:
a[~(a > a.mean())]    # ~ mean not so gives all elements not greater than the
                      # mean So, result is elements less than or equal to mean

array([0, 1])

In [89]:
a[(a == 0) | (a == 1)]    # Logical Orperation

array([0, 1])

In [90]:
a[(a <= 2) & (a % 2 ==0)]

array([0, 2])

In [91]:
A = np.random.randint(100, size=(3, 3))    #generates a random 3x3 matrix

In [92]:
A

array([[20, 37,  1],
       [41, 19,  2],
       [51,  5, 10]])

In [93]:
A > 30

array([[False,  True, False],
       [ True, False, False],
       [ True, False, False]])

In [94]:
A[A > 30]

array([37, 41, 51])

# **Linear Algebra**

In [95]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [96]:
B = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [97]:
A.dot(B)    #Dot product

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [98]:
A @ B   #Cross Product

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [99]:
B.T   #Transpose

array([[1, 3, 5],
       [2, 4, 6]])

In [100]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
B.T @ A

array([[48, 57, 66],
       [60, 72, 84]])

# **Useful Numpy Functions**



```
random
```





In [102]:
np.random.random(size=2)    #Return random floats in the half-open interval [0.0, 1.0).

array([0.94871128, 0.08643367])

In [103]:
np.random.normal(size=2)    #random.normal(loc=0.0, scale=1.0, size=None)
                            #Draw random samples from a normal (Gaussian) distribution.

array([ 1.33163176, -0.78520808])

In [104]:
np.random.rand(2, 4)    #Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

array([[0.38240778, 0.07107018, 0.19538494, 0.93260136],
       [0.80872639, 0.12202332, 0.18522669, 0.19922024]])



```
arange
```



In [105]:
np.arange(10)   #Create Array from 0 - 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.arange(5, 10)  #Create Array from 5 - 9

array([5, 6, 7, 8, 9])

In [107]:
np.arange(0, 1, .1)   #Create Array from 0 - 0.9 step .1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])



```
reshape
```



In [108]:
np.arange(10).reshape(2, 5)   #2D array with 2 sub arrays and 5 elements in each sub array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [109]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])



```
lineshape
```



In [126]:
np.linspace(0, 1, 5)    #Return evenly spaced numbers over a specified interval.
                        #numpy.linspace(start = 0, stop = 1, num=5, endpoint=True, 
                        #       retstep=False, dtype=None, axis=0)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [127]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [128]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])



```
zeros, ones, empty
```



In [110]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [111]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [112]:
np.zeros((3, 3), dtype=np.int_)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [113]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [114]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [117]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [116]:
np.empty((2, 2))

array([[0.e+000, 5.e-324],
       [0.e+000, 5.e-324]])



```
identity, eye
```



In [118]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [120]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [124]:
"Hello World"[6]

'W'